name: Build
description: Build base solr image
inputs:
  version:
    description: solr version
    required: true
  workdir:
    description: working directory
    required: true
  tags:
    description: image tags
    required: true
  username:
    description: docker username
    required: true
  password:
    description: docker password
    required: true
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      SOLR_VER: ${{ inputs.version }}
      DOCKER_USERNAME: ${{ inputs.username }}
      DOCKER_PASSWORD: ${{ inputs.password }}
      TAGS: ${{ inputs.tags }}
    run: |
      set -e
      make
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
    working-directory: ${{ inputs.workdir }}/alpine
